export const ClientInfo = [
    {
        picture: 'https://randomuser.me/api/portraits/men/1.jpg',
        name: 'David Kemp',
        age : 22,
        city: 'Birmingham',
        height: 182,
        weight: 86,
        blood: 'AB+',
        status: 'Needs Focus', 
    },
    {
        picture: 'https://randomuser.me/api/portraits/women/2.jpg',
        name: 'Sarah Johnson',
        age : 31,
        city: 'London',
        height: 165,
        weight: 68,
        blood: 'O+',
        status: 'Ok', 
    },
    {
        picture: 'https://randomuser.me/api/portraits/men/3.jpg',
        name: 'John Doe',
        age : 26,
        city: 'Manchester',
        height: 175,
        weight: 75,
        blood: 'A-',
        status: 'Good',
    },
    {
        picture: 'https://randomuser.me/api/portraits/women/4.jpg',
        name: 'Emily Davis',
        age : 40,
        city: 'Liverpool',
        height: 160,
        weight: 60,
        blood: 'B+',
        status: 'Excellent', 
    },
    {
        picture: 'https://randomuser.me/api/portraits/men/5.jpg',
        name: 'Michael Brown',
        age : 44,
        city: 'Leeds',
        height: 180,
        weight: 82,
        blood: 'O-',
        status: 'Needs Focus', 
    }
];