export  const fakeData = [
    {
        id: 1,
        externalLink: "/patientList/info-graphic",
        patient: "John Doe",
        memberId: "M123456",
        age: "30",
        sex: "Male",
        weight: "70kg",
        enroll: "2023-01-01",
        state: "Stable",
        followUp: "2023-05-20",
        heartRate: "72 bpm",
        pressure: "120/80 mmHg",
        temperature: "98.6°F",
        oxygen: "98%",
        respiration: "16 breaths/min",
        stateColor: "green",
        lastColor: "none",
        imageSrc: "https://example.com/image1.jpg",
        last: "2023-05-19"
    },
    {
        id: 2,
        externalLink: "https://example.com/link2",
        patient: "Jane Smith",
        memberId: "M654321",
        age: "45",
        sex: "Female",
        weight: "60kg",
        enroll: "2023-02-01",
        state: "Critical",
        followUp: "2023-05-21",
        heartRate: "90 bpm",
        pressure: "130/90 mmHg",
        temperature: "100.4°F",
        oxygen: "95%",
        respiration: "20 breaths/min",
        stateColor: "red",
        lastColor: "none",
        imageSrc: "https://example.com/image2.jpg",
        last: "2023-05-20"
    },
    {
        id: 3,
        externalLink: "https://example.com/link3",
        patient: "Alice Johnson",
        memberId: "M789012",
        age: "55",
        sex: "Female",
        weight: "65kg",
        enroll: "2023-03-01",
        state: "Stable",
        followUp: "2023-05-22",
        heartRate: "75 bpm",
        pressure: "125/85 mmHg",
        temperature: "99.1°F",
        oxygen: "97%",
        respiration: "18 breaths/min",
        stateColor: "green",
        lastColor: "none",
        imageSrc: "https://example.com/image3.jpg",
        last: "2023-05-21"
    },
    {
        id: 4,
        externalLink: "https://example.com/link4",
        patient: "Bob Williams",
        memberId: "M345678",
        age: "60",
        sex: "Male",
        weight: "80kg",
        enroll: "2023-04-01",
        state: "Moderate",
        followUp: "2023-05-23",
        heartRate: "85 bpm",
        pressure: "140/90 mmHg",
        temperature: "98.7°F",
        oxygen: "96%",
        respiration: "17 breaths/min",
        stateColor: "yellow",
        lastColor: "none",
        imageSrc: "https://example.com/image4.jpg",
        last: "2023-05-22"
    },
    {
        id: 5,
        externalLink: "https://example.com/link5",
        patient: "Charlie Brown",
        memberId: "M567890",
        age: "50",
        sex: "Male",
        weight: "75kg",
        enroll: "2023-05-01",
        state: "Stable",
        followUp: "2023-05-24",
        heartRate: "70 bpm",
        pressure: "118/78 mmHg",
        temperature: "98.4°F",
        oxygen: "99%",
        respiration: "15 breaths/min",
        stateColor: "green",
        lastColor: "none",
        imageSrc: "https://example.com/image5.jpg",
        last: "2023-05-23"
    },
    {
        id: 6,
        externalLink: "https://example.com/link6",
        patient: "Daisy Miller",
        memberId: "M234567",
        age: "40",
        sex: "Female",
        weight: "68kg",
        enroll: "2023-06-01",
        state: "Moderate",
        followUp: "2023-05-25",
        heartRate: "78 bpm",
        pressure: "122/80 mmHg",
        temperature: "99.5°F",
        oxygen: "97%",
        respiration: "16 breaths/min",
        stateColor: "yellow",
        lastColor: "none",
        imageSrc: "https://example.com/image6.jpg",
        last: "2023-05-24"
    }, {
        id: 1,
        externalLink: "https://example.com/link1",
        patient: "John Doe",
        memberId: "M123456",
        age: "30",
        sex: "Male",
        weight: "70kg",
        enroll: "2023-01-01",
        state: "Stable",
        followUp: "2023-05-20",
        heartRate: "72 bpm",
        pressure: "120/80 mmHg",
        temperature: "98.6°F",
        oxygen: "98%",
        respiration: "16 breaths/min",
        stateColor: "green",
        lastColor: "none",
        imageSrc: "https://example.com/image1.jpg",
        last: "2023-05-19"
    },
    {
        id: 2,
        externalLink: "https://example.com/link2",
        patient: "Jane Smith",
        memberId: "M654321",
        age: "45",
        sex: "Female",
        weight: "60kg",
        enroll: "2023-02-01",
        state: "Critical",
        followUp: "2023-05-21",
        heartRate: "90 bpm",
        pressure: "130/90 mmHg",
        temperature: "100.4°F",
        oxygen: "95%",
        respiration: "20 breaths/min",
        stateColor: "red",
        lastColor: "none",
        imageSrc: "https://example.com/image2.jpg",
        last: "2023-05-20"
    },
    {
        id: 3,
        externalLink: "https://example.com/link3",
        patient: "Alice Johnson",
        memberId: "M789012",
        age: "55",
        sex: "Female",
        weight: "65kg",
        enroll: "2023-03-01",
        state: "Stable",
        followUp: "2023-05-22",
        heartRate: "75 bpm",
        pressure: "125/85 mmHg",
        temperature: "99.1°F",
        oxygen: "97%",
        respiration: "18 breaths/min",
        stateColor: "green",
        lastColor: "none",
        imageSrc: "https://example.com/image3.jpg",
        last: "2023-05-21"
    },
    {
        id: 4,
        externalLink: "https://example.com/link4",
        patient: "Bob Williams",
        memberId: "M345678",
        age: "60",
        sex: "Male",
        weight: "80kg",
        enroll: "2023-04-01",
        state: "Moderate",
        followUp: "2023-05-23",
        heartRate: "85 bpm",
        pressure: "140/90 mmHg",
        temperature: "98.7°F",
        oxygen: "96%",
        respiration: "17 breaths/min",
        stateColor: "yellow",
        lastColor: "none",
        imageSrc: "https://example.com/image4.jpg",
        last: "2023-05-22"
    },
    {
        id: 5,
        externalLink: "https://example.com/link5",
        patient: "Charlie Brown",
        memberId: "M567890",
        age: "50",
        sex: "Male",
        weight: "75kg",
        enroll: "2023-05-01",
        state: "Stable",
        followUp: "2023-05-24",
        heartRate: "70 bpm",
        pressure: "118/78 mmHg",
        temperature: "98.4°F",
        oxygen: "99%",
        respiration: "15 breaths/min",
        stateColor: "green",
        lastColor: "none",
        imageSrc: "https://example.com/image5.jpg",
        last: "2023-05-23"
    },
    {
        id: 6,
        externalLink: "https://example.com/link6",
        patient: "Daisy Miller",
        memberId: "M234567",
        age: "40",
        sex: "Female",
        weight: "68kg",
        enroll: "2023-06-01",
        state: "Moderate",
        followUp: "2023-05-25",
        heartRate: "78 bpm",
        pressure: "122/80 mmHg",
        temperature: "99.5°F",
        oxygen: "97%",
        respiration: "16 breaths/min",
        stateColor: "yellow",
        lastColor: "none",
        imageSrc: "https://example.com/image6.jpg",
        last: "2023-05-24"
    },
    {
        id: 6,
        externalLink: "https://example.com/link6",
        patient: "Daisy Miller",
        memberId: "M234567",
        age: "40",
        sex: "Female",
        weight: "68kg",
        enroll: "2023-06-01",
        state: "Moderate",
        followUp: "2023-05-25",
        heartRate: "78 bpm",
        pressure: "122/80 mmHg",
        temperature: "99.5°F",
        oxygen: "97%",
        respiration: "16 breaths/min",
        stateColor: "yellow",
        lastColor: "none",
        imageSrc: "https://example.com/image6.jpg",
        last: "2023-05-24"
    },
    {
        id: 6,
        externalLink: "https://example.com/link6",
        patient: "Daisy Miller",
        memberId: "M234567",
        age: "40",
        sex: "Female",
        weight: "68kg",
        enroll: "2023-06-01",
        state: "Moderate",
        followUp: "2023-05-25",
        heartRate: "78 bpm",
        pressure: "122/80 mmHg",
        temperature: "99.5°F",
        oxygen: "97%",
        respiration: "16 breaths/min",
        stateColor: "yellow",
        lastColor: "none",
        imageSrc: "https://example.com/image6.jpg",
        last: "2023-05-24"
    }
    ,
    {
        id: 6,
        externalLink: "https://example.com/link6",
        patient: "Daisy Miller",
        memberId: "M234567",
        age: "40",
        sex: "Female",
        weight: "68kg",
        enroll: "2023-06-01",
        state: "Moderate",
        followUp: "2023-05-25",
        heartRate: "78 bpm",
        pressure: "122/80 mmHg",
        temperature: "99.5°F",
        oxygen: "97%",
        respiration: "16 breaths/min",
        stateColor: "green",
        lastColor: "none",
        imageSrc: "https://example.com/image6.jpg",
        last: "2023-05-24"
    },



    {
        id: 1,
        externalLink: "https://example.com/link1",
        patient: "John Doe",
        memberId: "M123456",
        age: "30",
        sex: "Male",
        weight: "70kg",
        enroll: "2023-01-01",
        state: "Stable",
        followUp: "2023-05-20",
        heartRate: "72 bpm",
        pressure: "120/80 mmHg",
        temperature: "98.6°F",
        oxygen: "98%",
        respiration: "16 breaths/min",
        stateColor: "green",
        lastColor: "none",
        imageSrc: "https://example.com/image1.jpg",
        last: "2023-05-19"
    },
    {
        id: 2,
        externalLink: "https://example.com/link2",
        patient: "Jane Smith",
        memberId: "M654321",
        age: "45",
        sex: "Female",
        weight: "60kg",
        enroll: "2023-02-01",
        state: "Critical",
        followUp: "2023-05-21",
        heartRate: "90 bpm",
        pressure: "130/90 mmHg",
        temperature: "100.4°F",
        oxygen: "95%",
        respiration: "20 breaths/min",
        stateColor: "red",
        lastColor: "none",
        imageSrc: "https://example.com/image2.jpg",
        last: "2023-05-20"
    },
    {
        id: 3,
        externalLink: "https://example.com/link3",
        patient: "Alice Johnson",
        memberId: "M789012",
        age: "55",
        sex: "Female",
        weight: "65kg",
        enroll: "2023-03-01",
        state: "Stable",
        followUp: "2023-05-22",
        heartRate: "75 bpm",
        pressure: "125/85 mmHg",
        temperature: "99.1°F",
        oxygen: "97%",
        respiration: "18 breaths/min",
        stateColor: "green",
        lastColor: "none",
        imageSrc: "https://example.com/image3.jpg",
        last: "2023-05-21"
    },
    {
        id: 4,
        externalLink: "https://example.com/link4",
        patient: "Bob Williams",
        memberId: "M345678",
        age: "60",
        sex: "Male",
        weight: "80kg",
        enroll: "2023-04-01",
        state: "Moderate",
        followUp: "2023-05-23",
        heartRate: "85 bpm",
        pressure: "140/90 mmHg",
        temperature: "98.7°F",
        oxygen: "96%",
        respiration: "17 breaths/min",
        stateColor: "yellow",
        lastColor: "none",
        imageSrc: "https://example.com/image4.jpg",
        last: "2023-05-22"
    },
    {
        id: 5,
        externalLink: "https://example.com/link5",
        patient: "Charlie Brown",
        memberId: "M567890",
        age: "50",
        sex: "Male",
        weight: "75kg",
        enroll: "2023-05-01",
        state: "Stable",
        followUp: "2023-05-24",
        heartRate: "70 bpm",
        pressure: "118/78 mmHg",
        temperature: "98.4°F",
        oxygen: "99%",
        respiration: "15 breaths/min",
        stateColor: "green",
        lastColor: "none",
        imageSrc: "https://example.com/image5.jpg",
        last: "2023-05-23"
    },
    {
        id: 6,
        externalLink: "https://example.com/link6",
        patient: "Daisy Miller",
        memberId: "M234567",
        age: "40",
        sex: "Female",
        weight: "68kg",
        enroll: "2023-06-01",
        state: "Moderate",
        followUp: "2023-05-25",
        heartRate: "78 bpm",
        pressure: "122/80 mmHg",
        temperature: "99.5°F",
        oxygen: "97%",
        respiration: "16 breaths/min",
        stateColor: "yellow",
        lastColor: "none",
        imageSrc: "https://example.com/image6.jpg",
        last: "2023-05-24"
    }, {
        id: 1,
        externalLink: "https://example.com/link1",
        patient: "John Doe",
        memberId: "M123456",
        age: "30",
        sex: "Male",
        weight: "70kg",
        enroll: "2023-01-01",
        state: "Stable",
        followUp: "2023-05-20",
        heartRate: "72 bpm",
        pressure: "120/80 mmHg",
        temperature: "98.6°F",
        oxygen: "98%",
        respiration: "16 breaths/min",
        stateColor: "green",
        lastColor: "none",
        imageSrc: "https://example.com/image1.jpg",
        last: "2023-05-19"
    },
    {
        id: 2,
        externalLink: "https://example.com/link2",
        patient: "Jane Smith",
        memberId: "M654321",
        age: "45",
        sex: "Female",
        weight: "60kg",
        enroll: "2023-02-01",
        state: "Critical",
        followUp: "2023-05-21",
        heartRate: "90 bpm",
        pressure: "130/90 mmHg",
        temperature: "100.4°F",
        oxygen: "95%",
        respiration: "20 breaths/min",
        stateColor: "red",
        lastColor: "none",
        imageSrc: "https://example.com/image2.jpg",
        last: "2023-05-20"
    },
    {
        id: 3,
        externalLink: "https://example.com/link3",
        patient: "Alice Johnson",
        memberId: "M789012",
        age: "55",
        sex: "Female",
        weight: "65kg",
        enroll: "2023-03-01",
        state: "Stable",
        followUp: "2023-05-22",
        heartRate: "75 bpm",
        pressure: "125/85 mmHg",
        temperature: "99.1°F",
        oxygen: "97%",
        respiration: "18 breaths/min",
        stateColor: "green",
        lastColor: "none",
        imageSrc: "https://example.com/image3.jpg",
        last: "2023-05-21"
    },
    {
        id: 4,
        externalLink: "https://example.com/link4",
        patient: "Bob Williams",
        memberId: "M345678",
        age: "60",
        sex: "Male",
        weight: "80kg",
        enroll: "2023-04-01",
        state: "Moderate",
        followUp: "2023-05-23",
        heartRate: "85 bpm",
        pressure: "140/90 mmHg",
        temperature: "98.7°F",
        oxygen: "96%",
        respiration: "17 breaths/min",
        stateColor: "yellow",
        lastColor: "none",
        imageSrc: "https://example.com/image4.jpg",
        last: "2023-05-22"
    },
    {
        id: 5,
        externalLink: "https://example.com/link5",
        patient: "Charlie Brown",
        memberId: "M567890",
        age: "50",
        sex: "Male",
        weight: "75kg",
        enroll: "2023-05-01",
        state: "Stable",
        followUp: "2023-05-24",
        heartRate: "70 bpm",
        pressure: "118/78 mmHg",
        temperature: "98.4°F",
        oxygen: "99%",
        respiration: "15 breaths/min",
        stateColor: "green",
        lastColor: "none",
        imageSrc: "https://example.com/image5.jpg",
        last: "2023-05-23"
    },
    {
        id: 6,
        externalLink: "https://example.com/link6",
        patient: "Daisy Miller",
        memberId: "M234567",
        age: "40",
        sex: "Female",
        weight: "68kg",
        enroll: "2023-06-01",
        state: "Moderate",
        followUp: "2023-05-25",
        heartRate: "78 bpm",
        pressure: "122/80 mmHg",
        temperature: "99.5°F",
        oxygen: "97%",
        respiration: "16 breaths/min",
        stateColor: "yellow",
        lastColor: "none",
        imageSrc: "https://example.com/image6.jpg",
        last: "2023-05-24"
    },
    {
        id: 6,
        externalLink: "https://example.com/link6",
        patient: "Daisy Miller",
        memberId: "M234567",
        age: "40",
        sex: "Female",
        weight: "68kg",
        enroll: "2023-06-01",
        state: "Moderate",
        followUp: "2023-05-25",
        heartRate: "78 bpm",
        pressure: "122/80 mmHg",
        temperature: "99.5°F",
        oxygen: "97%",
        respiration: "16 breaths/min",
        stateColor: "yellow",
        lastColor: "none",
        imageSrc: "https://example.com/image6.jpg",
        last: "2023-05-24"
    },
    {
        id: 6,
        externalLink: "https://example.com/link6",
        patient: "Daisy Miller",
        memberId: "M234567",
        age: "40",
        sex: "Female",
        weight: "68kg",
        enroll: "2023-06-01",
        state: "Moderate",
        followUp: "2023-05-25",
        heartRate: "78 bpm",
        pressure: "122/80 mmHg",
        temperature: "99.5°F",
        oxygen: "97%",
        respiration: "16 breaths/min",
        stateColor: "yellow",
        lastColor: "none",
        imageSrc: "https://example.com/image6.jpg",
        last: "2023-05-24"
    }
    ,
    {
        id: 6,
        externalLink: "https://example.com/link6",
        patient: "Daisy Miller",
        memberId: "M234567",
        age: "40",
        sex: "Female",
        weight: "68kg",
        enroll: "2023-06-01",
        state: "Moderate",
        followUp: "2023-05-25",
        heartRate: "78 bpm",
        pressure: "122/80 mmHg",
        temperature: "99.5°F",
        oxygen: "97%",
        respiration: "16 breaths/min",
        stateColor: "green",
        lastColor: "none",
        imageSrc: "https://example.com/image6.jpg",
        last: "2023-05-24"
    }
];
